<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net8.0</TargetFramework><GenerateDependencyFile>true</GenerateDependencyFile></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../DP.WorkFlow.Nodes.Vision/DP.WorkFlow.Nodes.Vision.csproj" />
    <ProjectReference Include="../../../../../DP.LabelInspection/src/DP.LabelInspection.Contracts/DP.LabelInspection.Contracts.csproj" />
  </ItemGroup>
</Project>
