<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net8.0-windows</TargetFramework><UseWPF>true</UseWPF></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../DP.WorkFlow.UI.Wpf/DP.WorkFlow.UI.Wpf.csproj" />
    <ProjectReference Include="../DP.WorkFlow.LabelInspection.UI/DP.WorkFlow.LabelInspection.UI.csproj" />
    <ProjectReference Include="../../../../../DP.LabelInspection/src/DP.LabelInspection.Runtime/DP.LabelInspection.Runtime.csproj" />
  </ItemGroup>
</Project>
