<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\DP.Vision\src\DP.Vision.Algorithms\DP.Vision.Algorithms.csproj" />
    <ProjectReference Include="..\..\Kernel\DP.WorkFlow.Abstractions\DP.WorkFlow.Abstractions.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
</Project>
